version: '3.4'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.backend
      args:
        DB_CONNECTION: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
        MODE: "TEST"
    entrypoint: >
      sh -c "sleep 5 && python ./studsched/main.py"
    volumes:
      - ../:/app/ 
    environment:
      - PYTHONPATH=/app/studsched
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/version"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
      - "db:db"
    depends_on:
      - db

  # frontend:
  #   build:
  #     context: ../
  #     dockerfile: ./docker/Dockerfile.frontend
  #     args:
  #       REACT_PORT: "${REACT_PORT}"
  #   ports:
  #     - "${REACT_PORT}:${REACT_PORT}"
  #   depends_on:
  #     - backend

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
