FROM node:14-alpine

WORKDIR /frontend
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
ENV PORT=3000
ENV REACT_APP_SERVER_URL=https://localhost:8000
ENV HOST=0.0.0.0
EXPOSE 3000
CMD ["npm", "start"]