version: '3.4'
name: student-scheduler-test

services:
  db:
    image: postgres:latest
    container_name: "${DB_CONTAINER_NAME}"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - "${DB_PORT}:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.backend
      args:
        DB_CONNECTION: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_CONTAINER_NAME}:5432/${POSTGRES_DB}"
        MODE: ${MODE}
    container_name: ${BACKEND_CONTAINER_NAME}
    entrypoint: >
      sh -c "sleep 5 && make test"
    volumes:
      - ../:/app/
    environment:
      - PYTHONPATH=/app/studsched
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/version"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
      - "db:db"
    depends_on:
      - db

